name: Tests

on:
  push:
    branches: [main]
    tags:
      - v*

  pull_request:
    branches: [main]

jobs:
  gen-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init git submodules
        run: make init-submodule

      - name: Run unit tests
        run: make test-ci

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: build-results
          path: proto-gen-*/
      - name: Upload to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: proto-gen-*/**/*
          tags: false
          draft: true
